//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.02 at 05:49:36 PM GMT 
//


package jk.tracker.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Profile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="show" type="{}Show" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="folders" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autotrack" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="autoupdate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="formats" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Profile", propOrder = {
    "show"
})
public class Profile {

    protected List<Show> show;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String folders;
    @XmlAttribute(required = true)
    protected boolean autotrack;
    @XmlAttribute(required = true)
    protected boolean autoupdate;
    @XmlAttribute(required = true)
    protected String formats;

    /**
     * Gets the value of the show property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the show property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Show }
     * 
     * 
     */
    public List<Show> getShow() {
        if (show == null) {
            show = new ArrayList<Show>();
        }
        return this.show;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the folders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolders() {
        return folders;
    }

    /**
     * Sets the value of the folders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolders(String value) {
        this.folders = value;
    }

    /**
     * Gets the value of the autotrack property.
     * 
     */
    public boolean isAutotrack() {
        return autotrack;
    }

    /**
     * Sets the value of the autotrack property.
     * 
     */
    public void setAutotrack(boolean value) {
        this.autotrack = value;
    }

    /**
     * Gets the value of the autoupdate property.
     * 
     */
    public boolean isAutoupdate() {
        return autoupdate;
    }

    /**
     * Sets the value of the autoupdate property.
     * 
     */
    public void setAutoupdate(boolean value) {
        this.autoupdate = value;
    }

    /**
     * Gets the value of the formats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormats() {
        return formats;
    }

    /**
     * Sets the value of the formats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormats(String value) {
        this.formats = value;
    }

}
